### ISSUE TITLE
Remove licensing from when it was a commercial product

### ISSUE THREAD

**Issue by jacobmesu** [ComponentFactory/Krypton#2]

**Comment by gliwka** [comment]
This can be closed now.

**Comment by Wagnerp** [comment]
This problem still exists in the 'PublisherSigned' binaries.

**Comment by gliwka** [comment]
In this case we need help from @ComponentFactory, since he's the only one with the ability to sign and build those. But those (PublisherSigned) are not really needed.

The only difference between those is, that the PublisherSigned ones are signed by @ComponentFactory. So you should be fine using the unsigned Build. If you need signed ones, just sign them yourself (https://msdn.microsoft.com/en-us/library/ms247123(v=vs.100).aspx)

**Comment by Wagnerp** [comment]
Thanks for your response, can I just remove the *.snk files and recompile? There is also a further issue, which I don't know is covered which means you can't drag controls to a form, as they act in a similar way to a timer, background worker and dialog controls. I'll have a look at the code today to see what's causing this behaviour.

**Comment by Cocotteseb** [comment]
Yes you can.
For design time support missing : you just need to register in the GAC the *.design.dll and voila !

**Comment by Wagnerp** [comment]
Thanks for that, maybe the wiki documentation or some sort of in depth guide need to be written to explain to users what to do. Just out of interest can I use GAC if I put all the relevant DLLs into a separate directory i.e. C:\Development\Krypton\bin?
