### ISSUE TITLE
MultiLine Property

### ISSUE THREAD

**Issue by holgworknote** [ComponentFactory/Krypton#27]
Looks like "MultiLine" property doesn't work with all Krypton controls. 
![scr](https://cloud.githubusercontent.com/assets/20695413/23538945/dc848c02-fff0-11e6-8739-55e63ac02025.PNG)

Or maybe im doing something wrong?

**Comment by mbagattini** [comment]
From the screenshot I read a "short text" proprerty, maybe there's a "long
text" too?

Il giorno ven 3 mar 2017 alle 06:09 holgworknote <notifications@github.com>
ha scritto:

**Comment by holgworknote** [comment]
With "long text"  MultiLine property doesn't work too.

**Comment by ghaberek** [comment]
The `KryptonLabel` control does not support wrapping. Use `KryptonWrapLabel` instead.

From the documentation (emphasis mine):

> ## KryptonWrapLabel
>
> Use the KryptonWrapLabel control when you need to functionality of the standard Windows.Forms.Label control but with the text color and font of the Krypton palette system. Unlike the KryptonLabel control this KryptonWrapLabel control inherits directly from the standard Windows.Forms.Label class and so it performs the same automatic wrapping of text onto multiple lines. This is the one circumstance for which this control is recommended instead of the KryptonLabel control. _**If you need text to span multiple lines then this is the control to use.**_

**Comment by holgworknote** [comment]
Okay, but how can I make multiline header description?

**Comment by greghaberek** [comment]
If you're talking about the `Description` field of a `KryptonHeader` control, you shouldn't have to change anything in the state settings. It will automatically support a multi-line value and should size itself correctly.

![image](https://cloud.githubusercontent.com/assets/7934662/24043704/4844777e-0aee-11e7-93f9-3d196845e5db.png)

If you want to specify a multi-line value using the designer, click the drop-down button next to the value, which provides a multi-line text editor.

![image](https://cloud.githubusercontent.com/assets/7934662/24043750/828f168c-0aee-11e7-8aca-e77bf614ec5c.png)

Otherwise you can just specify a line break in code, e.g.

    kryptonHeader1.ValuesPrimary.Description = "Description\nLine 2"

**Comment by holgworknote** [comment]
Thx, thats what i mean!
