### ISSUE TITLE
Controls not appear in VS2017

### ISSUE THREAD

**Issue by Burnsage** [ComponentFactory/Krypton#36]
Hello,
the controls are not visible in VS2017.

![Screenshot](https://i.imgur.com/OZHTNJe.png)

**Comment by Wagnerp** [comment]
Hi @Burnsage 

Did you register the DLLs with the GAC? If you did it may take some time for your PC to respond to this change. For me, I had to leave my PC for 24 hours before it worked, don't ask me why this happened because I genuinely have no clue.

**Comment by Burnsage** [comment]
Hey @Wagnerp,
yes, first I've executed the RegisterToGAC.bat file.

**Comment by Wagnerp** [comment]
Hi @Burnsage 

Thanks for replying, it may take a few hours and restarts to kick in. I think this is because Windows needs to 'flush' and rebuild the Global Assembly Cache. There's no easy way around this apart from waiting, or you could try the free 'gacview' tool available from http://www.nirsoft.net/dot_net_tools/gac_viewer.html to see if this works.

**Comment by Burnsage** [comment]
Oh okay, thank you. 👍
